language: cpp
compiler: gcc
sudo: false

env:
  global:
    - EPICS_BASE=$HOME/epics/base-3.14.12.5
    - EPICS_HOST_ARCH=linux-x86_64
  matrix:
    - BOOST=/usr
    - BOOST=""
    - BOOST=/usr EPICS_LIBCOM_ONLY=YES
    
cache:
  directories:
  - $HOME/epics
  - $HOME/synapps
  
addons:
  apt:
    packages:
    - libhdf5-serial-dev
    - libxml2-dev 
    - libboost-test-dev
  
before_install:
  #- sh ci/install-packages.sh     # Install 3rd party tools (lcov)
  - sh ci/build-epics.sh          # Download and build EPICS base (unless its cached)
  - if [ -z "$EPICS_LIBCOM_ONLY" ]; then sh ci/build-synapps-deps.sh ; fi  # Download and build synApps support modules like asyn, busy (unless its cached)
  - sh ci/configure.sh            # Prepare the configure/* files 
  - ls $HOME/epics
  - ls $HOME/synapps
  
install: 
  - pwd
  - make

# Run the tests
script:
  - if [ -f bin/$EPICS_HOST_ARCH/plugin-test ]; then ./bin/$EPICS_HOST_ARCH/plugin-test --log_level=test_suite ; fi

# If all worked then work out the coverage and update coveralls.io
#after_success:
#  - sh ci/coverage.sh
#  - coveralls-lcov --source-encoding=ISO-8859-1 ci/coverage.info
  
